### ISSUE TITLE
Folds are not saved on shutdown

### ISSUE THREAD

**Issue by Shaker-Hamdi** [forivall/atom-remember-folds#2] opened 2016-04-21 09:24 UTC
Atom used to remember code folding in version 1.5~, but I just updated to 1.7.2, and that feature is gone, so I searched for a solution and came across this package, but with no luck, it simply doesn't work. (_forivall edit: when completely closing and restarting atom_)

**Comment by megadr01d** [comment] 2016-04-22 02:03
^ Yup, not working on 1.7.2.
Still waiting for https://github.com/atom/atom/issues/8764

**Comment by forivall** [comment] 2016-04-22 20:52
Does the console show anything? It's still working fine for me, 1.7.2 on OSX, but not on my Laptop (1.6.something) on Arch. Might be a race condition, considering that my laptop is a potato.

**Comment by Shaker-Hamdi** [comment] 2016-04-23 12:27
I was working on version 1.5.2, and code folding remember state was working fine out of the box, no packages needed.
When I upgraded to 1.7.2 on my work machine (windows 8), that functionality disappeared, so when I searched fro a solution I came across your package, but it just didn't work.

I did a fresh installation of Atom 1.7.2 on my home machine (windows 10), after uninstalling old version completely, and just like on my work machine, I didn't find code fold remember state working out of the box, so I installed your package once again, but with no luck.

I really miss this feature.

And as for the console, there's no errors, just warnings, but not related to this package, here's the warnings though ...

`Window load time: 763ms
/C:/Users/Shaker/.atom/packages/emmet/lib/emmet.coffee:139 Loading Emmet extensions from ~/emmet
/C:/Users/Shaker/.atom/packages/emmet/lib/emmet.coffee:156 Emmet: no such extension folder: C:\Users\Shaker/emmet
/C:/Users/Shaker/.atom/packages/minimap/lib/minimap-element.js:1079 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
C:\Users\Shaker\AppData\Local\atom\app-1.7.2\resources\app.asar\src\text-editor-component.js:983 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.`

And as for disabling "editorconfig", please tell me where exactly I can do that so that I can try and see.

**Comment by Shaker-Hamdi** [comment] 2016-04-25 10:22
O.K, here's how to make it work.
1- open the file and fold the code.
2- close the file **without closing the app**.
3- re-open the file.
4- close the app.
5- re-open the app and it's working, the folded state is preserved.

It's weird, but that's how I got it to work (by luck).
if you folded the code the closed the app itself, then re-open the app the fold state won't be remembered.

**Comment by forivall** [comment] 2016-04-25 14:14
Yeah, the point of this package is to save state when closing and reopening tabs, not when closing and re opening the application. Since saving state when closing and reopening the application should be natively supported.

So, all this is is a documentation fix.

**Comment by jarodium** [comment] 2016-05-20 18:47
Can it be changed ( or setup a preference ) so that we can change this behavior?

**Comment by forivall** [comment] 2016-05-20 19:46
@jarodium I'd happily accept a PR that adds saving on startup/shutdown.

**Comment by BlizzzArt** [comment] 2016-05-27 19:03
my atom is 1.7.4 and this packages is sometimes works and sometimes not

**Comment by forivall** [comment] 2016-05-27 19:09
@BlizzzArt This package does not currently save folds on startup/shutdown. Does it work when you close a tab and re-open it without restarting? That is the main purpose of this package.

**Comment by BlizzzArt** [comment] 2016-05-29 15:37
Yes it's work. But commented out css is not, so it seemed to me that sometimes it's not work

**Comment by sudogem** [comment] 2016-06-24 15:06
I recently installed remember-folds package but it doesn't work on atom version 1.8.0 :(

**Comment by forivall** [comment] 2016-06-24 17:59
@sudogem please provide steps to reproduce, including what actions you perform, and what's expected.

**Comment by sudogem** [comment] 2016-06-25 16:40
From Install Package, i search remember-folds then click Install.. I open my sample ruby source code and try to fold some parts of my code. I close the file and my atom then re-open the editor again. Then check my ruby source code but it didnt fold.

**Comment by forivall** [comment] 2016-06-26 02:38
@sudogem @BlizzzArt If you have reproducible examples, please provide them with example files included in a gist and submit a new issue. If you are re-stating the initial issue, please use reactions instead of me-too comments, or at least say that it's a me-too comment. When you say "close", please specify if you mean close a tab, or close atom completely.

Unconstructive comments have been deleted.

**Comment by vzhen** [comment] 2016-10-27 12:47
Not working on me.
atom 1.11.2
Windows 7

**Comment by forivall** [comment] 2016-10-27 21:41
@vzhen you're free to write a PR. This is a confirmed bug, but it's low priority for me to fix.

**Closed** 2016-11-13 21:06 UTC
Labels: pr welcome

**Comment by forivall** [comment] 2016-11-14 06:34
I finally fixed this since I started noticing the issue. Published as 0.3.0. Let me know if any of y'all have more issues.

**Comment by WyattJordan** [comment] 2018-01-13 20:53
I am still having the same problem (Fold states aren't preserved upon closing and re-opening Atom). It works for closing and reopening the file in the same atom instance but not after restarting Atom

I am using the PlatformIO plugin to program an arduino  (I don't know if that info helps), any ideas?

**Comment by Shaker-Hamdi** [comment] 2018-01-13 20:56
@WyattJordan , Just switch to VSCode, man. I switched a long time ago, it rocks.

**Comment by WyattJordan** [comment] 2018-01-13 20:57
Does it have a lot of support for embedded systems? I only use Atom for the PlatformIO plug-in which supports over 400 different embedded boards

**Comment by Shaker-Hamdi** [comment] 2018-01-13 21:04
@WyattJordan I don't use it to code embedded systems, but as far as I know, it does have support for PlatformIO and embedded systems, you can check it out, it has tons of features.

**Comment by WyattJordan** [comment] 2018-01-13 21:17
@Shaker-Hamdi thanks, I'll look into it before I start my next big project!
